name = "Your Mod Name";
picture = "path\to\your\mod\logo.paa";					// Op: Logo for mod
// logoSmall = "path\to\your\mod\small_logo.paa";		// Op: Smaller version of  logo
// logo = "path\to\your\mod\large_logo.paa";			// Op: Larger version of logo
// logoOver = "path\to\your\mod\logo_hover.paa";		// Op: Logo for tooltip
tooltip = "This is your mod's tooltip text";			// Op
overview = "A brief overview of what your mod does";	// Op
// action = "https://more_info_about_mod.com";			// Op
author = "UbiquitousNull";
version = "0.0.1";
hideName = 0;											// 1 to hide the mod name 
hidePicture = 0;										// 1 to hide the mod picture 
dir = "@YourModName";
dependencies[] = {"Game", "World", "Mission"};			// Op
